language: ruby
rvm:
  - 2.2.0
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp config/application.yml.sample config/application.yml
  - psql -c 'create database blink_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: lYGI1tQj2ozT/mSUp+kIybgGB3/V2gbO3KVlb9CvfbPXUC6kzjPox+rRq3uRtXuoX6izccl5x+COnWl8A20RQMe6L7Rngk3Vd1WxChZf12hum63vSpJAFeLKLzX8ykTxv4y3pmKuIwDxFoPgks1ffU6qvVpb1ighERbLZudZlDYYENjID6ytmTkEBPaSiBkyf7lQkrFRmERDXjOVxMhKsRkmwl9ny+EU9OGlbQIFKcsaJAty/O3pwIDJ9MdeXsO27WrdfJ8B6sTMaOVaHEKzE47xU08xtBOP5y8YUSEJN5+0K6bFnscnI9gXJG+QphFPZg1rx64eyQJ8V41IDyAhWRI7sK5VFAwtz36T8JL7X4qv2uUtluyUtCx/odgBEAOCs3s6+Ag0yhE+S9R01MsffpLIPX1RDXdfLYugAOiQxoy+iGgr5uqrLptH84xM4dwNVVCiEty3gzUIhXOQ5JdYMks0sHmOcoDE9MITD/qw8bO/m5lMGGJNyuwvfLp75SZBwDI7U+o2WAYsD+F49zX89ikANfdFOgBaETlG0WbifqW2OFDWTq/2zaqZaz3NEexl2SAz8lI3Oi0bZ6+lyY5iPiKbxwfo0hTEIVLj98FTRV0D6puJ9W0JbHzUFOzxZwnlO7S2Gg9tokvFOYQAW7EgZMQt0q6ggSVCNhTT3eqeGDw=
  app: blink-ed
  on:
    repo: timothyandrew/blink
  run: "rake db:migrate"
  strategy: git
