language: ruby
rvm:
  - 2.2.2
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp config/application.yml.sample config/application.yml
  - psql -c 'create database blink_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: ayuWNls9WxnzQMa5BoG72bCTyFZIT74hX4A1ydICgdtwcm67OVzrBYS1KQ1Ockcshq3aS+wMiptWNJqtn+VWV8NYLlCKrWIUG2bqG+yA3SdRz6A7GdBx0VIrQD7+OzkZFTmEtj1Soj5hXwTxzxf9LP2TSDXIwCGitamkOBegya25b/spO2zDi3GM/J4QVDI8jRgPG2A9xpLYlI4r3Ig5t65vVV39ZAr4CfOmapTvrIHzzv6sr+olT8MHISN7vOODSrNc+WHj3kYVbAvDkThRcjZvxF4NEkR8LBu7GSVWpyev6oD4EWsu1ujcPVSMcMjARVtSlLnoGPPnN1x8cpmC94pQMqWp2AZWm9In3gK+/mRqSFypZa2EeNgH5CSfmMQvcFrniRLhO3xW65WCSjjbLf0WXkcBiYPkwbooZHZgW7BKux9qJY9BSU5ke43muMBrYDT2tNGeJQQ+TezmNBInBAzirGTPDsH2a4f8Mer8nVPSEp4QBRWV3+PeJV/6oqWUuRHwUmfDiJ/z69v+qPNpjqTMCChhYWhTg4Xo5qwwOCBiRClEoKladfX3IDeexvCRsKRZIJZrafrIxapr7hAfUldd/kH/bz84D/djyGAMT5hB6anDcDjWIiwcnpIGDXDf9JZz0JnetoI/JEzt6o25nnWPTgbdHbOTLZYLYO5WTAU=
  app: blink-ed
  on:
    repo: timothyandrew/blink
  run: "rake db:migrate"
  strategy: git
