language: ruby
rvm:
  - 2.2.2
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp config/application.yml.sample config/application.yml
  - psql -c 'create database blink_test;' -U postgres
addons:
  postgresql: "9.4"
