language: ruby
rvm:
  - 2.2.2
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp config/application.yml.sample config/application.yml
  - psql -c 'create database blink_test;' -U postgres
addons:
  postgresql: "9.4"
deploy:
  provider: heroku
  api_key:
    secure: "JWaogP/wCLBNY2KXkXVy1vBh8kJWQibFEGC6p7m8RH9KCaIK9wj19i8xCu8nFWXMfkJOz2mncJrtrMnXubwgb7j8Q6IrkefOvEKlU66iHZDBih7zAu+oooHI6mC/n/OozKR/mAKVV9okehJRZvm5K088AUYTACSO1pW6Kt4rBro0Fc3xQBiNDdi9qsJdA8XVk9vb7+TieWrnlGQDAa9DYmkErE3yMXRaBUHJRZ5vN0CEJ/5XICtAxzYyKWHznfZNBJVVNr9gKavKgKjmGUr5zFLGrBaUCmxS4URri2G2KH+Ox+HqtkWIXMir6eUDpHvZ0GgzZgf6MY7+6fcP9rHZfqlO+T4zsxFhOT2iiJsF53XX9bqRH9WH/qx7fAwBGCAXmu/HWnj2jAPMEnWAlamREAxHAmPsOUPeSw2pbsKoB8jTsOJI0bcWXsqgrqpKZaOkNtDV609bAEd1S4GYxbKx+PsfvCvp74xjrApgvka6+u4tCNKEkeXI/CvGASdL+OQx1PVhsS5EyPls/WffngldoWI2yxCPzg6Wyn720fwzmspAw4++BU41ioFXBzRA20zgvGi+kWCZmZPzxqz+wOc5pWFhPoUBs55GaQUfWwz5fPKIekuH5N5Ot+Ck5CWNaTBg61IxtRJFP0gEwDSRUKgJQb3wtxGVHlWtDtI7PFWybB8="
  app: blink-ed
  on:
    repo: timothyandrew/blink
  run: "rake db:migrate"
  strategy: git
